-- =====================================================================
-- Health Web Group Work OS - schema for Cloudflare D1 (SQLite).
--
-- Task and project management for an agency: clients, boards, items, people
-- and who can see what. Nothing clinical anywhere.
--
-- Ported from the PostgreSQL original. Differences worth knowing:
--   * ids are TEXT holding a UUID, generated by the Worker (SQLite has no
--     gen_random_uuid), so every insert supplies its own id
--   * timestamps are TEXT in ISO-8601 UTC, which sorts correctly as text
--     and matches what new Date().toISOString() produces in JavaScript
--   * booleans are INTEGER 0/1
--   * jsonb becomes TEXT holding JSON, read with json_extract()
-- Partial indexes, foreign keys and CHECK constraints all work as before.
-- =====================================================================

create table organisation (
    id                text primary key,
    name              text not null,
    retention_months  integer not null default 84,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table site (
    id                text primary key,
    organisation_id   text not null references organisation(id) on delete cascade,
    name              text not null,
    address           text,
    active            integer not null default 1,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_site_org on site(organisation_id);

create table app_user (
    id                   text primary key,
    organisation_id      text not null references organisation(id) on delete cascade,
    email                text not null,
    -- Null when the person signs in through Cloudflare Access, which is the
    -- normal case: no password means nothing to steal.
    password_hash        text,
    full_name            text not null,
    job_title            text,
    site_id              text references site(id) on delete set null,
    role                 text not null check (role in
                            ('ADMIN','MANAGER','MEMBER','VIEWER','GUEST')),
    status               text not null default 'ACTIVE'
                            check (status in ('ACTIVE','SUSPENDED','LEAVER')),
    must_change_password integer not null default 0,
    created_at           text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    last_login_at        text
);
create unique index uq_user_email on app_user(lower(email));
create index idx_user_org on app_user(organisation_id);

create table client (
    id                text primary key,
    organisation_id   text not null references organisation(id) on delete cascade,
    name              text not null,
    code              text not null,
    status            text not null default 'ACTIVE'
                        check (status in ('PROSPECT','ACTIVE','PAUSED','ARCHIVED')),
    colour            text not null default 'blue',
    contact_name      text,
    contact_email     text,
    contact_phone     text,
    website           text,
    address           text,
    notes             text,
    started_on        text,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create unique index uq_client_code on client(organisation_id, upper(code));
create index idx_client_org on client(organisation_id, status);

create table client_member (
    client_id         text not null references client(id) on delete cascade,
    user_id           text not null references app_user(id) on delete cascade,
    role_on_client    text not null default 'MEMBER' check (role_on_client in ('LEAD','MEMBER')),
    assigned_at       text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    primary key (client_id, user_id)
);
create index idx_client_member_user on client_member(user_id);

create table workspace (
    id                text primary key,
    organisation_id   text not null references organisation(id) on delete cascade,
    name              text not null,
    description       text,
    colour            text not null default 'teal',
    sort_order        integer not null default 0,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_workspace_org on workspace(organisation_id);

create table board (
    id                text primary key,
    workspace_id      text not null references workspace(id) on delete cascade,
    client_id         text references client(id) on delete set null,
    name              text not null,
    description       text,
    template          text not null check (template in
                        ('PROJECTS','PIPELINE','HIRING','RENEWALS','CUSTOM')),
    -- INTERNAL: anyone with access to that client
    -- CONFIDENTIAL: managers and admins
    -- RESTRICTED: named people only, whatever their role
    sensitivity       text not null default 'INTERNAL'
                        check (sensitivity in ('INTERNAL','CONFIDENTIAL','RESTRICTED')),
    sort_order        integer not null default 0,
    created_by        text references app_user(id) on delete set null,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_board_workspace on board(workspace_id);
create index idx_board_client on board(client_id);

create table board_member (
    board_id          text not null references board(id) on delete cascade,
    user_id           text not null references app_user(id) on delete cascade,
    permission        text not null default 'EDIT' check (permission in ('VIEW','EDIT','ADMIN')),
    primary key (board_id, user_id)
);

create table board_group (
    id                text primary key,
    board_id          text not null references board(id) on delete cascade,
    title             text not null,
    colour            text not null default 'blue',
    sort_order        integer not null default 0,
    collapsed         integer not null default 0
);
create index idx_group_board on board_group(board_id);

create table board_column (
    id                text primary key,
    board_id          text not null references board(id) on delete cascade,
    title             text not null,
    type              text not null check (type in
                        ('TEXT','LONG_TEXT','STATUS','PEOPLE','DATE','TIMELINE','NUMBER',
                         'DROPDOWN','CHECKBOX','FILE','LINK','DEPENDENCY','FORMULA')),
    settings          text not null default '{}',
    sort_order        integer not null default 0,
    width             integer not null default 160
);
create index idx_column_board on board_column(board_id);

create table item (
    id                text primary key,
    board_id          text not null references board(id) on delete cascade,
    group_id          text references board_group(id) on delete set null,
    parent_id         text references item(id) on delete cascade,
    client_id         text references client(id) on delete set null,
    title             text not null,
    sort_order        integer not null default 0,
    archived          integer not null default 0,
    created_by        text references app_user(id) on delete set null,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_item_board on item(board_id, archived);
create index idx_item_group on item(group_id);
create index idx_item_parent on item(parent_id);
create index idx_item_client on item(client_id);

create table cell (
    item_id           text not null references item(id) on delete cascade,
    column_id         text not null references board_column(id) on delete cascade,
    value             text not null default '{}',
    updated_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_by        text references app_user(id) on delete set null,
    primary key (item_id, column_id)
);
create index idx_cell_column on cell(column_id);

create table item_update (
    id                text primary key,
    item_id           text not null references item(id) on delete cascade,
    author_id         text references app_user(id) on delete set null,
    body              text not null,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_update_item on item_update(item_id, created_at desc);

-- Append only. Nothing in the Worker updates or deletes a row here.
create table activity_log (
    id                integer primary key autoincrement,
    entity_type       text not null,
    entity_id         text not null,
    board_id          text,
    actor_id          text references app_user(id) on delete set null,
    action            text not null,
    detail            text,
    before_value      text,
    after_value       text,
    occurred_at       text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_activity_entity on activity_log(entity_type, entity_id, occurred_at desc);
create index idx_activity_board on activity_log(board_id, occurred_at desc);

create table user_session (
    id                text primary key,
    user_id           text not null references app_user(id) on delete cascade,
    started_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    last_seen_at      text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    ended_at          text,
    end_reason        text check (end_reason is null or end_reason in ('SIGNED_OUT','EXPIRED'))
);
create index idx_session_user on user_session(user_id, started_at desc);
create index idx_session_open on user_session(last_seen_at) where ended_at is null;

create table time_entry (
    id                text primary key,
    user_id           text not null references app_user(id) on delete cascade,
    client_id         text references client(id) on delete set null,
    item_id           text references item(id) on delete set null,
    board_id          text references board(id) on delete set null,
    started_at        text not null,
    ended_at          text,
    minutes           integer,
    note              text,
    billable          integer not null default 1,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_time_user on time_entry(user_id, started_at desc);
create index idx_time_client on time_entry(client_id, started_at desc);
create index idx_time_item on time_entry(item_id);
-- One running timer per person, enforced by the database rather than by hope.
create unique index uq_time_running on time_entry(user_id) where ended_at is null;

create table todo (
    id            text primary key,
    user_id       text not null references app_user(id) on delete cascade,
    client_id     text references client(id) on delete set null,
    title         text not null,
    done          integer not null default 0,
    due_on        text,
    sort_order    integer not null default 0,
    created_at    text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    completed_at  text
);
create index idx_todo_user on todo(user_id, done, sort_order);

create table automation (
    id                text primary key,
    board_id          text not null references board(id) on delete cascade,
    name              text not null,
    trigger_config    text not null default '{}',
    action_config     text not null default '{}',
    enabled           integer not null default 1,
    created_at        text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create index idx_automation_board on automation(board_id);
